config/routes.rb
Danrent::Application.routes.draw do

  root to: 'properties#new'

  resources :properties, only: [:show, :index, :edit, :new] do
    member do
      get 'edit/details', to: 'properties#edit_details'
    end
  end

  resources :tenants, only: [] do
  end

  scope :user do
    get 'favorites', to: 'users/properties#favorites'
  end

  scope :tenant do
    get 'conversations', to: 'tenants/conversations#index', as: :tenant_conversations
    get 'dialogs',       to: 'tenants/dialogs#index'

    get 'dialogs/:id',   to: 'tenants/dialogs#show', as: :tenant_dialog

    get 'system/dialogs/:id',   to: 'system/dialogs#show',  as: :tenant_system_dialog
    get 'system/dialogs',       to: 'system/dialogs#index', as: :tenant_system_dialogs

  end

  scope :landlord do
    get 'manage',        to: 'landlords/properties#manage'
    get 'conversations', to: 'landlords/conversations#index', as: :landlord_conversations

    get 'dialogs/:id',   to: 'landlords/dialogs#show',  as: :landlord_dialog
    get 'dialogs',       to:  'landlords/dialogs#index', as: :landlord_dialogs

    get 'system/dialogs/:id',   to: 'system/dialogs#show',  as: :landlord_system_dialog
    get 'system/dialogs',       to: 'system/dialogs#index', as: :landlord_system_dialogs
  end

  resources :sessions, only: [:new, :destroy]  

end

app/views/box/link_box/_edit_details.html.erb
<%= link_to edit_property_path(0, mode: 'edit_location') do %>
	<div id="link-create-property-details" class="box rounded link_box selectable">
		<div class="upper">
			<h3>New property</h3>
		</div>

		<div class="middle">
			<%= image_tag "property/default_photo.png", width: 240 %>
		</div>
		<div class="lower">
			<h4><span class="icon-pencil"></span> Edit property</h4>				
		</div>
	</div>
<% end %>